### ISSUE TITLE
Restore Config

### ISSUE THREAD

**Issue by severindellsperger** [wemulate/wemulate#62]
**Is your feature request related to a problem? Please describe.**
No, its an enhancement.

**Describe the solution you'd like**
We introduce a restore command, which allows restoring the config, which can be found in the database.

To do so we use the ConfigController and the command 
- restore all connections and parameter (the whole device): ``` wemulate restore device```
- restore a specific connection and its parameters ```wemulate restore connection -n connection_name```

**Describe alternatives you've considered**
No alternative.

**Additional context**
Discussion was here: https://github.com/wemulate/wemulate/issues/53#issuecomment-1188671607

**Comment by severindellsperger** [comment]
After this feature is implemented, the install script has to be adapted: the cron job has to execute `wemulate restore device` after a restore and thus ensure that all the connections with its parameters get restored completely.

**Comment by jklaiber** [comment]
For the install script:

We can have a look at this commit: https://github.com/wemulate/wemulate/commit/d8b75eef66bb21425d0c88d60aeb8b0fc9885ddc 
And can restore the changes.
